Portal/Portal/Controllers/SubscriptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Portal.Controllers
{
    public class SubscriptionController : Controller
    {
        public IActionResult subscriber()
        {
            return View();
        }

        public async Task<IActionResult> Subscribe([FromForm] MemberPrescription memberDetail)
        {
            try
            {
                string Token = HttpContext.Request.Cookies["Token"];
                Client obj = new Client();
                HttpClient httpClient = obj.SubscriptionApi();
                using (var request = new HttpRequestMessage(new HttpMethod("POST"), "/api/Subcription/Subscribe"))
                {
                    //_data = new Data();
                    ViewBag.Message = null;
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
                    request.Headers.TryAddWithoutValidation("accept", "application/json;");

                    var str = Newtonsoft.Json.JsonConvert.SerializeObject(memberDetail);

                    request.Content = new StringContent(str);
                    request.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
                    var response = httpClient.SendAsync(request).Result;


                    if (response.IsSuccessStatusCode)
                    {
                        string responseData = response.Content.ReadAsStringAsync().Result;

                        ViewBag.Message = responseData;//"Your Subscription Accepted successfully";
                        return View("subscriber");
                    }
                    else
                        return View("Member", "Index");
                }
                return View("Member", "Login");
            }
            catch (Exception e)
            {
                Console.Write("Exception " + e);
                return RedirectToAction("Privacy", "Home");
            }
        }


        public IActionResult unsubscriber()
        {
            return View();
        }
        public async Task<IActionResult> UnSubscribe(int mid,int sid)
        {
            try
            { 
                string Token = HttpContext.Request.Cookies["Token"];
                Client obj = new Client();
                HttpClient httpClient = obj.SubscriptionApi();
                 using (var request = new HttpRequestMessage(new HttpMethod("POST"), "/api/Subcription/Unsubscribe?member_id="+mid+"&subscription_id="+sid))
                    {
                        request.Headers.TryAddWithoutValidation("accept", "text/plain");
                        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
                        request.Content = new StringContent("");
                        request.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/x-www-form-urlencoded");

                        var response = await httpClient.SendAsync(request);
                        if (response.IsSuccessStatusCode)
                        {
                            string responseData = response.Content.ReadAsStringAsync().Result;
                            ViewBag.Message = responseData;//"Your Succesfully Unsubscribe";
                            return View("unsubscriber");
                        }
                    }
            
                return View("Index","Member");
            }
            catch (Exception e)
            {
                Console.Write("Exception " + e);
                return RedirectToAction("Privacy", "Home");
            }
        }
        


    }
}

Portal/Portal/Views/Subscription/subscriber.cshtml
@model Portal.Models.MemberPrescription

@{ ViewData["Title"] = "subscriber"; }

<style>
    div form {
        display: block;
        margin-left: 400px;
        margin-right: 400px;
        width: 400px;
    }
</style>

<div class="login-form">
<div class="row">
    <div class="col-md-5">
    <form asp-action="Subscribe">

        <h2 class="text-center">Prescription Details</h2>
        <br />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="PrescriptionId" class="control-label"></label>

            <input asp-for="PrescriptionId" class="form-control" />
            <span asp-validation-for="PrescriptionId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MemberID" class="control-label"></label>

            <input asp-for="MemberID" class="form-control" />
            <span asp-validation-for="MemberID" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Insurance_Policy_Number" class="control-label"></label>

            <input asp-for="Insurance_Policy_Number" class="form-control" />
            <span asp-validation-for="Insurance_Policy_Number" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="InsuranceProvider" class="control-label"></label>

            <input asp-for="InsuranceProvider" class="form-control" />
            <span asp-validation-for="InsuranceProvider" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PrescriptionDate" class="control-label"></label>

            <input type="date" asp-for="PrescriptionDate" class="form-control" />
            <span asp-validation-for="PrescriptionDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="drugID" class="control-label"></label>

            <input asp-for="drugID" class="form-control" />
            <span asp-validation-for="drugID" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="dosage" class="control-label"></label>

            <input asp-for="dosage" class="form-control" />
            <span asp-validation-for="dosage" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PrescriptionCourse" class="control-label"></label>

            <input asp-for="PrescriptionCourse" class="form-control" />
            <span asp-validation-for="PrescriptionCourse" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Doctordetails" class="control-label"></label>

            <input asp-for="Doctordetails" class="form-control" />
            <span asp-validation-for="Doctordetails" class="text-danger"></span>
        </div>


        <div class="form-group">
            <input type="submit" value="Subscribe" class="btn btn-primary btn-block" />
        </div>
    </form>
        </div>
    </div>
</div>


@if (ViewBag.Message != null)
{



<script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
                window.location.href = "@Url.Action("subscriber", "Subscription")";
            };
</script>}

@section Scripts {
    <script>
        $(document).keypress(function (event) {

            var keycode = (event.keyCode ? event.keyCode : event.which);
            if (keycode == '13') {
                //window.location.href = "/salaryLogViewmodel/SalaryList";
                window.location.href = "/ubscription/subscriber";
            }

        });</script>
}

Portal/Portal/Views/Subscription/unsubscriber.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Portal.Models.MemberSubscription
@{ ViewData["Title"] = "unsubscriber"; }


<div class="login-form">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Unsubscribe" method="post">

                <h2 class="text-center">Enter Details To Unsubscribe Mail Order Service</h2>
                <br />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="MemberID" class="control-label"></label>

                    <input asp-for="MemberID" type="number" name="mid" class="form-control" />
                    <span asp-validation-for="MemberID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubscriptionId" class="control-label"></label>

                    <input asp-for="SubscriptionId" type="number" name="sid" class="form-control" />
                    <span asp-validation-for="SubscriptionId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Unsubscribe" class="btn btn-primary btn-block" />
                </div>
            </form>
            </div>
        </div>
        </div>


        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
                window.location.href = "@Url.Action("unsubscriber", "Subscription")";
            };
            </script>
        }

        @section Scripts {
            <script>
    $(document).keypress(function (event) {

                    var keycode = (event.keyCode ? event.keyCode : event.which);
                    if (keycode == '13') {
                        //window.location.href = "/salaryLogViewmodel/SalaryList";
                        window.location.href = "/Subscription/unsubscriber";
                    }

                });</script>
        }